POST http://localhost:8080/api/refresh-token/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjU1Nzk5NTI2LCJleHAiOjE2NTY0MDQzMjZ9.Xm6WbiH1MByLoc1_-apyE1fJf1ViWcA2AbjYmiyilvg