jwt:
  key:
    access: ZGFyYWUtamFuZy1qd3QtdHV0b3JpYWwtYWNjZXNzLXNlY3JldC1rZXk=
    refresh: ZGFyYWUtamFuZy1qd3QtdHV0b3JpYWwtcmVmcmVzaC1zZWNyZXQta2V5
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7