spring:
  profiles:
    include: jwt # application-jwt 에 해당하는 properties 혹은 yml 파일을 읽어온다.

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_example?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: springuser
    password: ThePassword

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug
    org.springframework.boot.autoconfigure: info
    org.apache.coyote.http11: debug
    tutorial.board: debug
